#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

kind: Service
apiVersion: v1
metadata:
  name: helidon-se-codeone-2018
  labels:
    app: helidon-se-codeone-2018
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080" 
spec:
  type: NodePort
  selector:
    app: helidon-se-codeone-2018
  ports:
  - port: 8080
    targetPort: 8080
    name: http 
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helidon-se-codeone-2018
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helidon-se-codeone-2018
        version: v1
    spec:
      containers:
      - name: helidon-se-codeone-2018
        image: iad.ocir.io/oracle-cloudnative/helidon-se-codeone-2018
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: helidon-se-codeone-2018
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - interval: 30s
    port: http
  jobLabel: helidon-se-codeone-2018
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: helidon-se-codeone-2018

